name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ['8.x']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies for main project
        run: dotnet restore WebCityEvents/WebCityEvents.csproj

      - name: Restore dependencies for test project
        run: dotnet restore WebCityEvents.Tests/WebCityEvents.Tests.csproj

      - name: Build main project
        run: dotnet build WebCityEvents/WebCityEvents.csproj --no-restore

      - name: Build test project
        run: dotnet build WebCityEvents.Tests/WebCityEvents.Tests.csproj --no-restore

      - name: Test
        run: dotnet test WebCityEvents.Tests/WebCityEvents.Tests.csproj --no-restore --verbosity normal